#!/usr/bin/env bash

## Install ansible Debian
# sudo apt-add-repository -y ppa:ansible/ansible
# sudo apt-get update -y
# sudo apt-get install -y curl git software-properties-common ansible

sudo pacman -S curl git ansible

## pull ansible
# sudo ansible-pull -U https://github.com/v01dv/ansible.git
