- hosts: localhost
  pre_tasks:
    - name: Full system upgrade
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
        state: present
      tags:
        - install
        - core
  tasks:  
    - include: tasks/core-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/postinstall-setup.yml

