- name: Install X11
  become: true
  pacman:
    name: ["xorg-server", "xorg-server-devel", "xorg-xdpyinfo", "xorg-xinit", "xorg-xrandr", "xorg-xsetroot", "xdg-user-dirs"]
  tags:
    - install
    - core
    - x11

- name: Install System Packages 1 (picom, dunst, lxsession, xwallpaper, xcape)
  become: true
  pacman:
    name: ["picom", "libnotify", "dunst", "lxsession", "xwallpaper", "xcape"]
  tags:
    - install
    - core

- name: Install System Packages 2 (zip, uzip, p7zip, wget, curl)
  become: true
  pacman:
    name: [ "zip", "unzip", "p7zip", "wget", "curl" ]
  tags:
    - install
    - core

- name: Install System Packages 3 (the rest)
  become: true
  pacman:
    name: [ "cifs-utils", "highlight" ]
  tags:
    - install
    - core

- name: Install clang
  become: true
  pacman:
    name: ["clang"]
  tags:
    - install
    - core
    - nvim

- name: Install bluetooth 
  become: true
  pacman:
    name: ["bluez", "bluez-utils"]
  tags:
    - install
    - core
    - bluetooth

- name: Install audio
  become: true
  pacman:
    name: [ "alsa-utils", "pulseaudio", "pulseaudio-alsa", "pulseaudio-bluetooth", "pamixer" ]
  tags:
    - install
    - core
    - audio

