- name: Installing stow
  pacman: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/v01dv/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: . arch
  args:
    chdir: $HOME/.dotfiles
    executable: /usr/bin/bash
  tags:
    - install
    - dotfiles
    - stow
