# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  # - import_tasks: users/voldv.yml

  ## desktop environments

  ## window manager 
  - include_tasks: window_managers/dwm/dwm.yml
   when: dwm is defined and dwm == true

  rescue:
    - set_fact: task_failed=true
