- name: users | voldv | create group
  tags: groups,voldv,users
  group:
    name: voldv 
    state: present

- name: users | voldv | create user
  tags: voldv,sudo,users
  user:
    name: voldv
    group: voldv
    groups: "{{ sudo_group }}"
    state: present
    #comment: "Jay Bkack"
    password: "{{ voldv_passwd }}"
    shell: /bin/bash

- name: users | voldv | add sudoers file
  tags: voldv,settings,sudo,system,users
  copy:
    src: users/sudoers_voldv
    dest: /etc/sudoers.d/voldv
    owner: root
    group: root
    mode: 0440

- name: users | voldv | create .ssh directory
  tags: dotfiles,voldv,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: voldv
    group: voldv
    mode: 0700
  with_items:
    - { dir: '/home/voldv/.ssh' }

- name : users | voldv | find all ssh private keys
  tags: dotfiles,voldv,ssh,ssh-keys,users
  find:
    paths: "{{ role_path }}/files/users/voldv/ssh"
    file_type: file
    patterns:  '^id_[^.]*$'
    use_regex: yes
  register: output

- name: users | voldv | copy private keys
  tags: dotfiles,voldv,ssh,ssh-keys,users
  copy:
    src: "{{ item.path }}"
    dest: /home/voldv/.ssh
    owner: voldv
    group: voldv
    mode: 0600
  with_items: "{{ output.files }}"

- name: users | voldv | copy public keys
  tags: dotfiles,voldv,ssh,ssh-keys,users
  copy:
    src: "{{ item }}"
    dest: /home/voldv/.ssh
    owner: voldv
    group: voldv
    mode: 0644
  with_fileglob:
    - "{{ role_path }}/files/users/voldv/ssh/*.pub"

- name: users | voldv | add public key
  tags: dotfiles,voldv,ssh,ssh-keys,users
  authorized_key:
    user: voldv
    key: "{{ item }}"
  with_file:
    - users/voldv/ssh/id_ed25519.pub

- name: users | voldv | remove preinstalled system files from home directory
  file:
    path: /home/voldv/{{ item }}
    state: absent
  with_items:
    - .bash_history
    - .bash_logout
    - .bash_profile

- name: users | voldv | create config directories
  tags: dotfiles,voldv,users
  file:
    path: /home/voldv/{{ item.dir }}
    state: directory
    owner: voldv
    group: voldv
    mode: 0700
  with_items:
    - { dir: '.local' }
    - { dir: '.local/share/password-store' }

- name: users | voldv | copy user scripts 
  tags: dotfiles,voldv,users
  copy:
    src: /home/voldv/.dotfiles/bin/.local/bin/
    dest: /home/voldv/.local/bin/
    owner: voldv
    group: voldv
    mode: 0644
    directory_mode:
