- name: users | voldv | create group
  tags: groups,voldv,users
  group:
    name: voldv 
    state: present

- name: users | voldv | create user
  tags: voldv,sudo,users
  user:
    name: voldv
    group: voldv
    groups: "{{ sudo_group }}"
    state: present
    #comment: "Jay Bkack"
    password: "{{ voldv_passwd }}"
    shell: /bin/bash

- name: users | voldv | add sudoers file
  tags: voldv,settings,sudo,system,users
  copy:
    src: users/sudoers_voldv
    dest: /etc/sudoers.d/voldv
    owner: root
    group: root
    mode: 0440

- name: users | voldv | create .ssh directory
  tags: dotfiles,voldv,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: voldv
    group: voldv
    mode: 0700
  with_items:
    - { dir: '/home/voldv/.ssh' }

- name: users | voldv | add public key
  tags: dotfiles,voldv,ssh,ssh-keys,users
  authorized_key:
    user: voldv
    key: "{{ item }}"
  with_file:
    - users/voldv/ssh/id_ed25519_github.pub
