- name: dwm | clone dwm sources
  tags: dwm
  become_user : voldv
  ansible.builtin.git:
    repo: 'git://git.suckless.org/dwm'
    dest: "/home/voldv/repos/dwm/"
    recursive: yes
    update: yes
    accept_hostkey: yes
    # version: main

- name: dwmblocks | clone dwmblocks sources
  tags: dwm,dwmblocks
  become_user : voldv
  ansible.builtin.git:
    repo: 'https://github.com/v01dv/dwmblocks'
    dest: "/home/voldv/repos/dwmblocks/"
    recursive: yes
    update: yes
    accept_hostkey: yes
    # version: main

- name: dwm | compile dwm and dwmblocks from sources
  tags: dwm, dwmblocks
  loop:
    - dwm
    - dwmblocks
  shell: make clean install 
  args:
    chdir: /home/voldv/repos/{{ item }}
