- name: users | ensure stow installed 
  tags: dotfiles,dotfiles-voldv,stow
  package: 
    state: present
    name: stow

- name: users | ensure git installed 
  tags: dotfiles,dotfiles-voldv,git
  package: 
    state: present
    name: git

- name: users | ensure dotfiles repository is cloned locally
  tags: dotfiles,dotfiles-voldv
  ansible.builtin.git:
    repo: 'https://github.com/v01dv/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: users | deploy base dotfiles
  tags: dotfiles,dotfiles-voldv
  environment:
    STOW_DIR: "{{ lookup('env', 'HOME') }}/.dotfiles"
  shell: |
    stow -D { item }
    stow { item }
  changed_when: false
  with_items: "{{ dotfiles_files }}"
